/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CER"
 * 	found in "CER.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Certificate_H_
#define	_Certificate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include "IssuerId.h"
#include "TbsCert.h"
#include "Signature.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Certificate */
typedef struct Certificate {
	Uint8_t	 version;
	IssuerId_t	 issuer;
	TbsCert_t	 tbs;
	Signature_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Certificate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Certificate;
extern asn_SEQUENCE_specifics_t asn_SPC_Certificate_specs_1;
extern asn_TYPE_member_t asn_MBR_Certificate_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _Certificate_H_ */
#include <asn_internal.h>
