/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "BASE"
 * 	found in "BASE.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_EccCurve_H_
#define	_EccCurve_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EccCurve {
	EccCurve_sgdsm2	= 0,
	EccCurve_nistP256	= 1,
	EccCurve_brainpoolP256r1	= 2
	/*
	 * Enumeration is extensible
	 */
} e_EccCurve;

/* EccCurve */
typedef long	 EccCurve_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EccCurve_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EccCurve;
extern const asn_INTEGER_specifics_t asn_SPC_EccCurve_specs_1;
asn_struct_free_f EccCurve_free;
asn_struct_print_f EccCurve_print;
asn_constr_check_f EccCurve_constraint;
ber_type_decoder_f EccCurve_decode_ber;
der_type_encoder_f EccCurve_encode_der;
xer_type_decoder_f EccCurve_decode_xer;
xer_type_encoder_f EccCurve_encode_xer;
oer_type_decoder_f EccCurve_decode_oer;
oer_type_encoder_f EccCurve_encode_oer;
per_type_decoder_f EccCurve_decode_uper;
per_type_encoder_f EccCurve_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EccCurve_H_ */
#include <asn_internal.h>
