/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "BASE"
 * 	found in "BASE.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ECCPoint_H_
#define	_ECCPoint_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NULL.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ECCPoint_PR {
	ECCPoint_PR_NOTHING,	/* No components present */
	ECCPoint_PR_x_only,
	ECCPoint_PR_fill,
	ECCPoint_PR_compressed_y_0,
	ECCPoint_PR_compressed_y_1,
	ECCPoint_PR_uncompressedP256
} ECCPoint_PR;

/* ECCPoint */
typedef struct ECCPoint {
	ECCPoint_PR present;
	union ECCPoint_u {
		OCTET_STRING_t	 x_only;
		NULL_t	 fill;
		OCTET_STRING_t	 compressed_y_0;
		OCTET_STRING_t	 compressed_y_1;
		struct uncompressedP256 {
			OCTET_STRING_t	 x;
			OCTET_STRING_t	 y;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} uncompressedP256;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ECCPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECCPoint;
extern asn_CHOICE_specifics_t asn_SPC_ECCPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_ECCPoint_1[5];
extern asn_per_constraints_t asn_PER_type_ECCPoint_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ECCPoint_H_ */
#include <asn_internal.h>
