/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecMsg"
 * 	found in "SecMsg.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_EciesEncryptedKey_H_
#define	_EciesEncryptedKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EccCurve.h"
#include "ECCPoint.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EciesEncryptedKey */
typedef struct EciesEncryptedKey {
	EccCurve_t	 eccCcurve;
	ECCPoint_t	 v;
	OCTET_STRING_t	 c;
	OCTET_STRING_t	 t;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EciesEncryptedKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EciesEncryptedKey;
extern asn_SEQUENCE_specifics_t asn_SPC_EciesEncryptedKey_specs_1;
extern asn_TYPE_member_t asn_MBR_EciesEncryptedKey_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _EciesEncryptedKey_H_ */
#include <asn_internal.h>
