/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "BASE"
 * 	found in "BASE.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_ElevationSec_H_
#define	_ElevationSec_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint16.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ElevationSec */
typedef Uint16_t	 ElevationSec_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ElevationSec_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ElevationSec;
asn_struct_free_f ElevationSec_free;
asn_struct_print_f ElevationSec_print;
asn_constr_check_f ElevationSec_constraint;
ber_type_decoder_f ElevationSec_decode_ber;
der_type_encoder_f ElevationSec_encode_der;
xer_type_decoder_f ElevationSec_decode_xer;
xer_type_encoder_f ElevationSec_encode_xer;
oer_type_decoder_f ElevationSec_decode_oer;
oer_type_encoder_f ElevationSec_encode_oer;
per_type_decoder_f ElevationSec_decode_uper;
per_type_encoder_f ElevationSec_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ElevationSec_H_ */
#include <asn_internal.h>
