/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecMsg"
 * 	found in "SecMsg.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_HeaderInfo_H_
#define	_HeaderInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "HashAlgorithm.h"
#include "Time64.h"
#include "HashedId3.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ThreeDLocation;
struct PublicEncryptionKey;

/* HeaderInfo */
typedef struct HeaderInfo {
	long	 itsAid;
	HashAlgorithm_t	*hashAlg	/* OPTIONAL */;
	Time64_t	*genTime	/* OPTIONAL */;
	Time64_t	*expiryTime	/* OPTIONAL */;
	struct ThreeDLocation	*location	/* OPTIONAL */;
	HashedId3_t	*digest	/* OPTIONAL */;
	struct PublicEncryptionKey	*encKey	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HeaderInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HeaderInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_HeaderInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_HeaderInfo_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ThreeDLocation.h"
#include "PublicEncryptionKey.h"

#endif	/* _HeaderInfo_H_ */
#include <asn_internal.h>
