/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CER"
 * 	found in "CER.asn"
 * 	`asn1c -gen-PER`
 */

#include "IssuerId.h"

static asn_oer_constraints_t asn_OER_type_IssuerId_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_IssuerId_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_IssuerId_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IssuerId, choice.self),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"self"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IssuerId, choice.certificateDigest),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CertificateDigest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certificateDigest"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_IssuerId_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* self */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* certificateDigest */
};
asn_CHOICE_specifics_t asn_SPC_IssuerId_specs_1 = {
	sizeof(struct IssuerId),
	offsetof(struct IssuerId, _asn_ctx),
	offsetof(struct IssuerId, present),
	sizeof(((struct IssuerId *)0)->present),
	asn_MAP_IssuerId_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_IssuerId = {
	"IssuerId",
	"IssuerId",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_IssuerId_constr_1, &asn_PER_type_IssuerId_constr_1, CHOICE_constraint },
	asn_MBR_IssuerId_1,
	2,	/* Elements count */
	&asn_SPC_IssuerId_specs_1	/* Additional specs */
};

