/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecMsg"
 * 	found in "SecMsg.asn"
 * 	`asn1c -gen-PER`
 */

#include "Payload.h"

static asn_oer_constraints_t asn_OER_type_Payload_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Payload_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_Payload_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Payload, choice.unSecuredData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Opaque,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unSecuredData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Payload, choice.signedData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignedData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signedData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Payload, choice.encData),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EncryptedData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"encData"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Payload_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* unSecuredData */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* signedData */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* encData */
};
asn_CHOICE_specifics_t asn_SPC_Payload_specs_1 = {
	sizeof(struct Payload),
	offsetof(struct Payload, _asn_ctx),
	offsetof(struct Payload, present),
	sizeof(((struct Payload *)0)->present),
	asn_MAP_Payload_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Payload = {
	"Payload",
	"Payload",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Payload_constr_1, &asn_PER_type_Payload_constr_1, CHOICE_constraint },
	asn_MBR_Payload_1,
	3,	/* Elements count */
	&asn_SPC_Payload_specs_1	/* Additional specs */
};

