/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecMsg"
 * 	found in "SecMsg.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Payload_H_
#define	_Payload_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Opaque.h"
#include "SignedData.h"
#include "EncryptedData.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Payload_PR {
	Payload_PR_NOTHING,	/* No components present */
	Payload_PR_unSecuredData,
	Payload_PR_signedData,
	Payload_PR_encData
} Payload_PR;

/* Payload */
typedef struct Payload {
	Payload_PR present;
	union Payload_u {
		Opaque_t	 unSecuredData;
		SignedData_t	 signedData;
		EncryptedData_t	 encData;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Payload_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Payload;
extern asn_CHOICE_specifics_t asn_SPC_Payload_specs_1;
extern asn_TYPE_member_t asn_MBR_Payload_1[3];
extern asn_per_constraints_t asn_PER_type_Payload_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Payload_H_ */
#include <asn_internal.h>
