/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_Uint3;
extern struct asn_TYPE_descriptor_s asn_DEF_KnownLatitude;
extern struct asn_TYPE_descriptor_s asn_DEF_UnknownLatitude;
extern struct asn_TYPE_descriptor_s asn_DEF_KnownLongitude;
extern struct asn_TYPE_descriptor_s asn_DEF_UnknownLongitude;
extern struct asn_TYPE_descriptor_s asn_DEF_SecuredMessage;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module BASE in BASE.asn */
	&asn_DEF_Uint3,	
	&asn_DEF_KnownLatitude,	
	&asn_DEF_UnknownLatitude,	
	&asn_DEF_KnownLongitude,	
	&asn_DEF_UnknownLongitude,	
	/* From module SecMsg in SecMsg.asn */
	&asn_DEF_SecuredMessage,	
	0
};

