/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecMsg"
 * 	found in "SecMsg.asn"
 * 	`asn1c -gen-PER`
 */

#include "PreSharedKeyRecipientInfo.h"

asn_TYPE_member_t asn_MBR_PreSharedKeyRecipientInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PreSharedKeyRecipientInfo, hashAlg),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HashAlgorithm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hashAlg"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PreSharedKeyRecipientInfo, symKeyHash),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HashedId8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"symKeyHash"
		},
};
static const ber_tlv_tag_t asn_DEF_PreSharedKeyRecipientInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PreSharedKeyRecipientInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* hashAlg */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* symKeyHash */
};
asn_SEQUENCE_specifics_t asn_SPC_PreSharedKeyRecipientInfo_specs_1 = {
	sizeof(struct PreSharedKeyRecipientInfo),
	offsetof(struct PreSharedKeyRecipientInfo, _asn_ctx),
	asn_MAP_PreSharedKeyRecipientInfo_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PreSharedKeyRecipientInfo = {
	"PreSharedKeyRecipientInfo",
	"PreSharedKeyRecipientInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_PreSharedKeyRecipientInfo_tags_1,
	sizeof(asn_DEF_PreSharedKeyRecipientInfo_tags_1)
		/sizeof(asn_DEF_PreSharedKeyRecipientInfo_tags_1[0]), /* 1 */
	asn_DEF_PreSharedKeyRecipientInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_PreSharedKeyRecipientInfo_tags_1)
		/sizeof(asn_DEF_PreSharedKeyRecipientInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PreSharedKeyRecipientInfo_1,
	2,	/* Elements count */
	&asn_SPC_PreSharedKeyRecipientInfo_specs_1	/* Additional specs */
};

