/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "BASE"
 * 	found in "BASE.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_PublicVerifyKey_H_
#define	_PublicVerifyKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EccCurve.h"
#include "ECCPoint.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PublicVerifyKey */
typedef struct PublicVerifyKey {
	EccCurve_t	 curve;
	ECCPoint_t	 key;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PublicVerifyKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PublicVerifyKey;
extern asn_SEQUENCE_specifics_t asn_SPC_PublicVerifyKey_specs_1;
extern asn_TYPE_member_t asn_MBR_PublicVerifyKey_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PublicVerifyKey_H_ */
#include <asn_internal.h>
