/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecMsg"
 * 	found in "SecMsg.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SecuredMessage_H_
#define	_SecuredMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include "Payload.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SecuredMessage */
typedef struct SecuredMessage {
	Uint8_t	 version;
	Payload_t	 payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecuredMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecuredMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _SecuredMessage_H_ */
#include <asn_internal.h>
