/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "BASE"
 * 	found in "BASE.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SequenceOfitsAidSspList_H_
#define	_SequenceOfitsAidSspList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ItsAidSsp;

/* SequenceOfitsAidSspList */
typedef struct SequenceOfitsAidSspList {
	A_SEQUENCE_OF(struct ItsAidSsp) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfitsAidSspList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfitsAidSspList;
extern asn_SET_OF_specifics_t asn_SPC_SequenceOfitsAidSspList_specs_1;
extern asn_TYPE_member_t asn_MBR_SequenceOfitsAidSspList_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ItsAidSsp.h"

#endif	/* _SequenceOfitsAidSspList_H_ */
#include <asn_internal.h>
