/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecMsg"
 * 	found in "SecMsg.asn"
 * 	`asn1c -gen-PER`
 */

#include "SignerInfo.h"

static asn_oer_constraints_t asn_OER_type_SignerInfo_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SignerInfo_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SignerInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SignerInfo, choice.self),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"self"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignerInfo, choice.certificateList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SequenceOfCertificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certificateList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignerInfo, choice.certificateDigest),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CertificateDigest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"certificateDigest"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SignerInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* self */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* certificateList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* certificateDigest */
};
asn_CHOICE_specifics_t asn_SPC_SignerInfo_specs_1 = {
	sizeof(struct SignerInfo),
	offsetof(struct SignerInfo, _asn_ctx),
	offsetof(struct SignerInfo, present),
	sizeof(((struct SignerInfo *)0)->present),
	asn_MAP_SignerInfo_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SignerInfo = {
	"SignerInfo",
	"SignerInfo",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_SignerInfo_constr_1, &asn_PER_type_SignerInfo_constr_1, CHOICE_constraint },
	asn_MBR_SignerInfo_1,
	3,	/* Elements count */
	&asn_SPC_SignerInfo_specs_1	/* Additional specs */
};

