/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CER"
 * 	found in "CER.asn"
 * 	`asn1c -gen-PER`
 */

#include "SubjectType.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_SubjectType_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SubjectType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_SubjectType_value2enum_1[] = {
	{ 0,	20,	"enrollmentCredential" },
	{ 1,	19,	"authorizationTicket" },
	{ 2,	22,	"authorizationAuthority" },
	{ 3,	19,	"enrollmentAuthority" },
	{ 4,	6,	"rootCa" },
	{ 5,	9,	"crlSigner" },
	{ 6,	15,	"pseudonymTicket" },
	{ 7,	18,	"pseudonymAuthority" }
};
static const unsigned int asn_MAP_SubjectType_enum2value_1[] = {
	2,	/* authorizationAuthority(2) */
	1,	/* authorizationTicket(1) */
	5,	/* crlSigner(5) */
	3,	/* enrollmentAuthority(3) */
	0,	/* enrollmentCredential(0) */
	7,	/* pseudonymAuthority(7) */
	6,	/* pseudonymTicket(6) */
	4	/* rootCa(4) */
};
const asn_INTEGER_specifics_t asn_SPC_SubjectType_specs_1 = {
	asn_MAP_SubjectType_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_SubjectType_enum2value_1,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_SubjectType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_SubjectType = {
	"SubjectType",
	"SubjectType",
	&asn_OP_NativeEnumerated,
	asn_DEF_SubjectType_tags_1,
	sizeof(asn_DEF_SubjectType_tags_1)
		/sizeof(asn_DEF_SubjectType_tags_1[0]), /* 1 */
	asn_DEF_SubjectType_tags_1,	/* Same as above */
	sizeof(asn_DEF_SubjectType_tags_1)
		/sizeof(asn_DEF_SubjectType_tags_1[0]), /* 1 */
	{ &asn_OER_type_SubjectType_constr_1, &asn_PER_type_SubjectType_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_SubjectType_specs_1	/* Additional specs */
};

