/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CER"
 * 	found in "CER.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SubjectType_H_
#define	_SubjectType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SubjectType {
	SubjectType_enrollmentCredential	= 0,
	SubjectType_authorizationTicket	= 1,
	SubjectType_authorizationAuthority	= 2,
	SubjectType_enrollmentAuthority	= 3,
	SubjectType_rootCa	= 4,
	SubjectType_crlSigner	= 5,
	SubjectType_pseudonymTicket	= 6,
	SubjectType_pseudonymAuthority	= 7
} e_SubjectType;

/* SubjectType */
typedef long	 SubjectType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SubjectType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SubjectType;
extern const asn_INTEGER_specifics_t asn_SPC_SubjectType_specs_1;
asn_struct_free_f SubjectType_free;
asn_struct_print_f SubjectType_print;
asn_constr_check_f SubjectType_constraint;
ber_type_decoder_f SubjectType_decode_ber;
der_type_encoder_f SubjectType_encode_der;
xer_type_decoder_f SubjectType_decode_xer;
xer_type_encoder_f SubjectType_encode_xer;
oer_type_decoder_f SubjectType_decode_oer;
oer_type_encoder_f SubjectType_encode_oer;
per_type_decoder_f SubjectType_decode_uper;
per_type_encoder_f SubjectType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SubjectType_H_ */
#include <asn_internal.h>
