/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CER"
 * 	found in "CER.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SubjectInfo_H_
#define	_SubjectInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SubjectType.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SubjectInfo */
typedef struct SubjectInfo {
	SubjectType_t	 subjectType;
	OCTET_STRING_t	 subjectName;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SubjectInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubjectInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_SubjectInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SubjectInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SubjectInfo_H_ */
#include <asn_internal.h>
