/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecMsg"
 * 	found in "SecMsg.asn"
 * 	`asn1c -gen-PER`
 */

#include "SymmetricCipherText.h"

static asn_oer_constraints_t asn_OER_type_SymmetricCipherText_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SymmetricCipherText_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SymmetricCipherText_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SymmetricCipherText, choice.sm4Ecb),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CipherText,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sm4Ecb"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SymmetricCipherText, choice.sm4Cbc),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SM4CipherText,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sm4Cbc"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SymmetricCipherText, choice.sm4Cfb),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SM4CipherText,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sm4Cfb"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SymmetricCipherText, choice.sm4Ofb),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SM4CipherText,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sm4Ofb"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SymmetricCipherText, choice.aesCcm),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AesCcmCipherText,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aesCcm"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SymmetricCipherText_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sm4Ecb */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sm4Cbc */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sm4Cfb */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sm4Ofb */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* aesCcm */
};
asn_CHOICE_specifics_t asn_SPC_SymmetricCipherText_specs_1 = {
	sizeof(struct SymmetricCipherText),
	offsetof(struct SymmetricCipherText, _asn_ctx),
	offsetof(struct SymmetricCipherText, present),
	sizeof(((struct SymmetricCipherText *)0)->present),
	asn_MAP_SymmetricCipherText_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SymmetricCipherText = {
	"SymmetricCipherText",
	"SymmetricCipherText",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_SymmetricCipherText_constr_1, &asn_PER_type_SymmetricCipherText_constr_1, CHOICE_constraint },
	asn_MBR_SymmetricCipherText_1,
	5,	/* Elements count */
	&asn_SPC_SymmetricCipherText_specs_1	/* Additional specs */
};

