/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CER"
 * 	found in "CER.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TbsCert_H_
#define	_TbsCert_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SubjectInfo.h"
#include "SubjectAttribute.h"
#include "ValidityRestriction.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TbsCert */
typedef struct TbsCert {
	SubjectInfo_t	 subjectInfo;
	SubjectAttribute_t	 subjectAttributes;
	ValidityRestriction_t	 validityRestrictions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TbsCert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TbsCert;
extern asn_SEQUENCE_specifics_t asn_SPC_TbsCert_specs_1;
extern asn_TYPE_member_t asn_MBR_TbsCert_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _TbsCert_H_ */
#include <asn_internal.h>
