/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SecMsg"
 * 	found in "SecMsg.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TBSData_H_
#define	_TBSData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HeaderInfo.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TBSData */
typedef struct TBSData {
	HeaderInfo_t	 headerInfo;
	OCTET_STRING_t	*data	/* OPTIONAL */;
	OCTET_STRING_t	*extHash	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TBSData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TBSData;
extern asn_SEQUENCE_specifics_t asn_SPC_TBSData_specs_1;
extern asn_TYPE_member_t asn_MBR_TBSData_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _TBSData_H_ */
#include <asn_internal.h>
