/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CER"
 * 	found in "CER.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TimeStartAndEnd_H_
#define	_TimeStartAndEnd_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Time32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TimeStartAndEnd */
typedef struct TimeStartAndEnd {
	Time32_t	 startValidity;
	Time32_t	 endValidity;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimeStartAndEnd_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeStartAndEnd;
extern asn_SEQUENCE_specifics_t asn_SPC_TimeStartAndEnd_specs_1;
extern asn_TYPE_member_t asn_MBR_TimeStartAndEnd_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TimeStartAndEnd_H_ */
#include <asn_internal.h>
