/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SPATIntersectionState"
 * 	found in "SPATIntersectionState.asn"
 * 	`asn1c -gen-PER`
 */

#include "Phase.h"

asn_TYPE_member_t asn_MBR_Phase_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Phase, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhaseID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Phase, phaseStates),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhaseStateList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"phaseStates"
		},
};
static const ber_tlv_tag_t asn_DEF_Phase_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Phase_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* phaseStates */
};
asn_SEQUENCE_specifics_t asn_SPC_Phase_specs_1 = {
	sizeof(struct Phase),
	offsetof(struct Phase, _asn_ctx),
	asn_MAP_Phase_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Phase = {
	"Phase",
	"Phase",
	&asn_OP_SEQUENCE,
	asn_DEF_Phase_tags_1,
	sizeof(asn_DEF_Phase_tags_1)
		/sizeof(asn_DEF_Phase_tags_1[0]), /* 1 */
	asn_DEF_Phase_tags_1,	/* Same as above */
	sizeof(asn_DEF_Phase_tags_1)
		/sizeof(asn_DEF_Phase_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Phase_1,
	2,	/* Elements count */
	&asn_SPC_Phase_specs_1	/* Additional specs */
};

