/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SPATIntersectionState"
 * 	found in "SPATIntersectionState.asn"
 * 	`asn1c -gen-PER`
 */

#include "TimeChangeDetails.h"

static asn_oer_constraints_t asn_OER_type_TimeChangeDetails_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_TimeChangeDetails_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_TimeChangeDetails_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TimeChangeDetails, choice.counting),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeCountingDown,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"counting"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeChangeDetails, choice.utcTiming),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTCTiming,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utcTiming"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TimeChangeDetails_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* counting */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* utcTiming */
};
asn_CHOICE_specifics_t asn_SPC_TimeChangeDetails_specs_1 = {
	sizeof(struct TimeChangeDetails),
	offsetof(struct TimeChangeDetails, _asn_ctx),
	offsetof(struct TimeChangeDetails, present),
	sizeof(((struct TimeChangeDetails *)0)->present),
	asn_MAP_TimeChangeDetails_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TimeChangeDetails = {
	"TimeChangeDetails",
	"TimeChangeDetails",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_TimeChangeDetails_constr_1, &asn_PER_type_TimeChangeDetails_constr_1, CHOICE_constraint },
	asn_MBR_TimeChangeDetails_1,
	2,	/* Elements count */
	&asn_SPC_TimeChangeDetails_specs_1	/* Additional specs */
};

