/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SPATIntersectionState"
 * 	found in "SPATIntersectionState.asn"
 * 	`asn1c -gen-PER`
 */

#include "TimeCountingDown.h"

asn_TYPE_member_t asn_MBR_TimeCountingDown_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TimeCountingDown, startTime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeMark,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"startTime"
		},
	{ ATF_POINTER, 2, offsetof(struct TimeCountingDown, minEndTime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeMark,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"minEndTime"
		},
	{ ATF_POINTER, 1, offsetof(struct TimeCountingDown, maxEndTime),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeMark,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxEndTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeCountingDown, likelyEndTime),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeMark,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"likelyEndTime"
		},
	{ ATF_POINTER, 3, offsetof(struct TimeCountingDown, timeConfidence),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Confidence,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeConfidence"
		},
	{ ATF_POINTER, 2, offsetof(struct TimeCountingDown, nextStartTime),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeMark,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nextStartTime"
		},
	{ ATF_POINTER, 1, offsetof(struct TimeCountingDown, nextDuration),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeMark,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nextDuration"
		},
};
static const int asn_MAP_TimeCountingDown_oms_1[] = { 1, 2, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_TimeCountingDown_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TimeCountingDown_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* startTime */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* minEndTime */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* maxEndTime */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* likelyEndTime */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* timeConfidence */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* nextStartTime */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* nextDuration */
};
asn_SEQUENCE_specifics_t asn_SPC_TimeCountingDown_specs_1 = {
	sizeof(struct TimeCountingDown),
	offsetof(struct TimeCountingDown, _asn_ctx),
	asn_MAP_TimeCountingDown_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_TimeCountingDown_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TimeCountingDown = {
	"TimeCountingDown",
	"TimeCountingDown",
	&asn_OP_SEQUENCE,
	asn_DEF_TimeCountingDown_tags_1,
	sizeof(asn_DEF_TimeCountingDown_tags_1)
		/sizeof(asn_DEF_TimeCountingDown_tags_1[0]), /* 1 */
	asn_DEF_TimeCountingDown_tags_1,	/* Same as above */
	sizeof(asn_DEF_TimeCountingDown_tags_1)
		/sizeof(asn_DEF_TimeCountingDown_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TimeCountingDown_1,
	7,	/* Elements count */
	&asn_SPC_TimeCountingDown_specs_1	/* Additional specs */
};

