/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SPATIntersectionState"
 * 	found in "SPATIntersectionState.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_TimeChangeDetails_H_
#define	_TimeChangeDetails_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeCountingDown.h"
#include "UTCTiming.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeChangeDetails_PR {
	TimeChangeDetails_PR_NOTHING,	/* No components present */
	TimeChangeDetails_PR_counting,
	TimeChangeDetails_PR_utcTiming
	/* Extensions may appear below */
	
} TimeChangeDetails_PR;

/* TimeChangeDetails */
typedef struct TimeChangeDetails {
	TimeChangeDetails_PR present;
	union TimeChangeDetails_u {
		TimeCountingDown_t	 counting;
		UTCTiming_t	 utcTiming;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimeChangeDetails_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeChangeDetails;
extern asn_CHOICE_specifics_t asn_SPC_TimeChangeDetails_specs_1;
extern asn_TYPE_member_t asn_MBR_TimeChangeDetails_1[2];
extern asn_per_constraints_t asn_PER_type_TimeChangeDetails_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeChangeDetails_H_ */
#include <asn_internal.h>
