/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VehEmgExt"
 * 	found in "VehEmgExt.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_VehicleEmergencyExtensions_H_
#define	_VehicleEmergencyExtensions_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ResponseType.h"
#include "SirenInUse.h"
#include "LightbarInUse.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleEmergencyExtensions */
typedef struct VehicleEmergencyExtensions {
	ResponseType_t	*responseType	/* OPTIONAL */;
	SirenInUse_t	*sirenUse	/* OPTIONAL */;
	LightbarInUse_t	*lightsUse	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleEmergencyExtensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleEmergencyExtensions;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleEmergencyExtensions_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleEmergencyExtensions_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleEmergencyExtensions_H_ */
#include <asn_internal.h>
