/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VehEmgExt"
 * 	found in "VehEmgExt.asn"
 * 	`asn1c -gen-PER`
 */

#include "VehicleEmergencyExtensions.h"

asn_TYPE_member_t asn_MBR_VehicleEmergencyExtensions_1[] = {
	{ ATF_POINTER, 3, offsetof(struct VehicleEmergencyExtensions, responseType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ResponseType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"responseType"
		},
	{ ATF_POINTER, 2, offsetof(struct VehicleEmergencyExtensions, sirenUse),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SirenInUse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sirenUse"
		},
	{ ATF_POINTER, 1, offsetof(struct VehicleEmergencyExtensions, lightsUse),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LightbarInUse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lightsUse"
		},
};
static const int asn_MAP_VehicleEmergencyExtensions_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_VehicleEmergencyExtensions_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VehicleEmergencyExtensions_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* responseType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sirenUse */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* lightsUse */
};
asn_SEQUENCE_specifics_t asn_SPC_VehicleEmergencyExtensions_specs_1 = {
	sizeof(struct VehicleEmergencyExtensions),
	offsetof(struct VehicleEmergencyExtensions, _asn_ctx),
	asn_MAP_VehicleEmergencyExtensions_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_VehicleEmergencyExtensions_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_VehicleEmergencyExtensions = {
	"VehicleEmergencyExtensions",
	"VehicleEmergencyExtensions",
	&asn_OP_SEQUENCE,
	asn_DEF_VehicleEmergencyExtensions_tags_1,
	sizeof(asn_DEF_VehicleEmergencyExtensions_tags_1)
		/sizeof(asn_DEF_VehicleEmergencyExtensions_tags_1[0]), /* 1 */
	asn_DEF_VehicleEmergencyExtensions_tags_1,	/* Same as above */
	sizeof(asn_DEF_VehicleEmergencyExtensions_tags_1)
		/sizeof(asn_DEF_VehicleEmergencyExtensions_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_VehicleEmergencyExtensions_1,
	3,	/* Elements count */
	&asn_SPC_VehicleEmergencyExtensions_specs_1	/* Additional specs */
};

